bugfix: include configuration to apply specify rules to style files
techexpertspro/portal-ascepa pull request #112
Opened 2024-07-06 13:29 UTC by LuccasTraumer

## Descrição

Incluindo configuração especifica aos arquivos de estilos, para que as regras de validações sejam especificar para este tipo de arquivo.
---

## Tipo da alteração

fix: Ajustando as validações do tipo scss

---

## Checklist

- [X] Revi meu próprio código antes de enviar para revisão
- [X] Testei minha correção ou recurso extensivamente antes de enviar para revisão
- [X] Meu código está bem documentado com apenas informações relevantes
- [X] Minhas alterações não geram novos avisos
- [X] Meus commits são bem organizados, descritivos e fáceis de reverter

---

2024-07-08 21:51 UTC, andrewarosario requested changes

2024-07-08 21:51 UTC, andrewarosario commented on package.json
> +    "lint": "nx lint && nx affected:lint --fix=true --uncommitted && nx test && nx format:write --uncommited"
O script executa o `nx lint` (somente na app principal) e depois o `nx affected:lint` que roda em todos os projetos afetados. O lint acaba rodando duas vezes. Teria algum motivo para isso?
Caso contrário acho que podemos deixar somente o `affected:lint` :)

2024-07-22 14:23 UTC, andrewarosario approved these changes

2024-07-22 18:59 UTC, Werisu approved these changes

2024-07-22 21:58 UTC, merged