feat(card): add card component
techexpertspro/portal-ascepa pull request #127
Opened 2024-07-28 19:16 UTC by arthuralveso

## Descrição

Add card component to the shared-ui module.

## Tipo da alteração

feat: add card component

---

## Checklist

- [x] Revi meu próprio código antes de enviar para revisão
- [x] Testei minha correção ou recurso extensivamente antes de enviar para revisão
- [x] Formatei meu código usando o guia de estilo de interface (Prettier + ESLint)
- [x] Meu código está bem documentado com apenas informações relevantes
- [x] Minhas alterações não geram novos avisos
- [x] Meus commits são bem organizados, descritivos e fáceis de reverter
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Meu código está seguindo os padrões de acessibilidade

---

## Outras observações

---

2024-07-29 12:44 UTC, andrewarosario requested changes

2024-07-29 12:44 UTC, andrewarosario commented on modules/shared-ui/src/lib/card.component.ts
Para mantermos uma melhor organização da estrutura de diretórios dos componentes, é legal mover o componente de card para uma pasta dele. Os arquivos ficariam nesse diretório:
```
modules/shared-ui/src/lib/card/card.component.ts
modules/shared-ui/src/lib/card/card.component.html
modules/shared-ui/src/lib/card/card.component.scss
modules/shared-ui/src/lib/card/card.component.spec.ts
```

2024-07-29 22:06 UTC, arthuralveso commented on modules/shared-ui/src/lib/card.component.ts
Acabei esquecendo de criar o folder dele. Resolvido

2024-07-29 23:14 UTC, andrewarosario approved these changes

2024-07-29 23:19 UTC, ernaneaugusto commented on modules/shared-ui/src/index.ts
> +export * from './lib/card.component';
Faltou o path /card no caminho export do componente card.
`export * from './lib/card/card.component'`

2024-07-29 23:40 UTC, ernaneaugusto commented on modules/shared-ui/src/lib/card/card.component.scss
> +  max-width: 389px;
Acho que seria bacana alterar o max-width=389px para width=100% para que o card ocupe sempre todo o espaço disponível, por exemplo:

- Com max-width fixo, se tivermos dois cards lado a lado e um container de 1200px cada parte terá 600px, mas o card terá o máximo de 389px(como está no momento) e não ocupará todo o conteúdo disponível.
- Com width=100% o card sempre ocupará 100% do espaço disponível para ele, deixando que seu container trabalhe em sua largura.

2024-07-29 23:44 UTC, ernaneaugusto commented on modules/shared-ui/src/lib/card/card.component.scss
> +    h3 {
[SUGESTÃO]
Usar o mixin headline-3-style na tag h3, pois ele já tem as configurações para  font-size,  font-weight e color.

2024-07-29 23:59 UTC, ernaneaugusto commented on modules/shared-ui/src/lib/card/card.component.scss
> +    p {
Criar uma classe que tenha os estilos:
font-size: $font-size-body-l;
font-weight: $font-weight-regular;
line-height: 24px;
text-align: left; // esse atributo pode remover, nesse caso o padrão do text-align já é left ^^

Adicionar aos dois parágrafos dentro de:
&__subtitle
&__description

Ambos tem a mesma formatação. Alterar apenas a **cor** específica de cada um que será diferente.

2024-07-30 00:01 UTC, ernaneaugusto commented on modules/shared-ui/src/lib/card/card.component.scss
> +    max-width: 265px;
Se foi alterado o max-width para width conforme sugestão para layout desktop pode remover o max-width do responsivo.

2024-07-30 00:07 UTC, ernaneaugusto commented on modules/shared-ui/src/lib/card/card.component.scss
> +  border-radius: 8px;
[SUGESTÃO]
O border-radius=8px está parecendo ser padrão para algumas coisas na nossa aplicação, como imagens, card e outros.

Criar o arquivo de variáveis genéricas no SCSS para padronizar esses estilos. Poderia ser em `src/scss/tokens/generic/_token.scss`.

2024-07-30 00:18 UTC, ernaneaugusto commented on modules/shared-ui/src/lib/card/card.component.html
> +    <div class="card__title">
[SUGESTÃO]
As divs card__title, card__subtitle e card__description tem apenas textos em seu conteúdo, com isso você poderia removê-las e usar apenas as tahs h3 e p que estão dentro de cada uma, melhorando assim a semântica do código e adicionando as devidas classes nelas:

**Atual:**
```
<div class="card__title">
  <h3>{{ title }}</h3>
</div>

<div class="card__subtitle">
  <p>{{ subtitle }}</p>
</div>

<div class="card__description">
  <p>
    {{ description }}
  </p>
</div>
```

**Sugerida:**
```
<h3 class="card__title">{{ title }}</h3>
<p class="card__subtitle">{{ subtitle }}</p>
<p class="card__description">{{ description }}</p>
```

2024-07-30 00:31 UTC, arthuralveso commented on modules/shared-ui/src/lib/card/card.component.html
> +    <div class="card__title">
Massa. Vou alterar.

2024-07-30 12:04 UTC, Werisu approved these changes
LGTM 🚀

2024-07-30 13:30 UTC, charlesribeiro commented
O nome do branch é _feat/card_ [feat/card](https://github.com/techexpertspro/portal-ascepa/tree/feat/card). Temos alguma convenção a respeito de nome de branch (por exemplo, de precisar conter a id da task relacionada)?

2024-07-30 14:08 UTC, andrewarosario commented on modules/shared-ui/src/lib/card/card.component.ts
> +  handleClick(buttonType: string) {
Ótimo ponto @charlesribeiro! Nesse caso, as propriedades do Button nós sabemos que serão somente `primary` e `secondary`.
Pra evitar complexidade, eu não vejo problema em deixar os tipos diretamente no componente. Exemplo:
```ts
@Input() buttonType: 'primary' | 'secondary';
```

2024-07-30 14:10 UTC, andrewarosario commented
> O nome do branch é _feat/card_ [feat/card](https://github.com/techexpertspro/portal-ascepa/tree/feat/card). Temos alguma convenção a respeito de nome de branch (por exemplo, de precisar conter a id da task relacionada)?

Não temos uma convenção pra isso. A princípio estamos criando como `<type>/<nome-da-alteração>`. Mas está totalmente aberto isso, se quiser podemos discutir em um Discussions 😉

2024-08-01 15:01 UTC, paoloalmeida commented on modules/shared-ui/src/lib/card/card.component.scss
> +  max-width: 389px;
Ajustes muito bem pontuados @ernaneaugusto ! 
Acho válido inclusive colocarmos uma nova task pra fazer esses ajustes, e já dar uma olhada geral pra padronizar com os valores e variáveis. O que acha?

2024-08-01 15:04 UTC, paoloalmeida commented on modules/shared-ui/src/lib/card/card.component.ts
> +  handleClick(buttonType: string) {
Show! Faz sentido time. O que você acha mestre @arthuralveso, faz sentido alterar aí?

2024-08-06 01:38 UTC, ernaneaugusto commented on modules/shared-ui/src/lib/card/card.component.scss
> +  max-width: 389px;
Acho válido sim é uma boa. Caso essa correção fique demorada podemos puxar em uma task de ajustes.

2024-08-11 21:59 UTC, arthuralveso commented on modules/shared-ui/src/lib/card/card.component.scss
> +    h3 {
Feito!

2024-08-11 22:00 UTC, arthuralveso commented on modules/shared-ui/src/lib/card/card.component.scss
> +    max-width: 265px;
ok

2024-08-11 22:59 UTC, arthuralveso commented on modules/shared-ui/src/lib/card/card.component.scss
> +  border-radius: 8px;
Boa! Resolvido

2024-08-11 23:02 UTC, arthuralveso commented on modules/shared-ui/src/lib/card/card.component.ts
> +  handleClick(buttonType: string) {
Boa, pessoal. Fazendo a alteração da tipagem.

2024-08-11 23:29 UTC, arthuralveso commented on modules/shared-ui/src/lib/card/card.component.scss
> +    h3 {
Na verdade não é necessário. Ja existe a importação dos mixins nas tags h1, h2 e h3 e ja estão nos estilos globais. Apenas removi o que ja tem no mixin. Valeu!

2024-08-12 18:58 UTC, andrewarosario approved these changes

2024-08-15 18:29 UTC, ernaneaugusto approved these changes

2024-08-15 18:34 UTC, merged