test(Cypress): Correction/Implementation of E2E Tests.
techexpertspro/portal-ascepa pull request #133
Opened 2024-07-31 23:55 UTC by FelipeDuarteLuna

## Descrição

Correção e implementação dos Testes E2E com Cypress.
![image](https://github.com/user-attachments/assets/ed3b3f47-ae3c-4c92-bd54-a3d2c2ba53f3)

Documentação criada relacionado aos Testes E2E com Cypress: https://github.com/techexpertspro/portal-ascepa/wiki/Cypress-%E2%80%90-Teste-E2E-(End%E2%80%90to%E2%80%90End)

---

## Tipo da alteração

test: Adicionando testes ausentes ou corrigindo testes existentes. (**Corrigindo os testes iniciais E2E e implementando um case test**).

---

## Checklist

- [ X ] Revi meu próprio código antes de enviar para revisão
- [ X ] Testei minha correção ou recurso extensivamente antes de enviar para revisão
- [ X ] Formatei meu código usando o guia de estilo de interface (Prettier + ESLint)
- [ X ] Meu código está bem documentado com apenas informações relevantes
- [ X ] Minhas alterações não geram novos avisos
- [ X ] Meus commits são bem organizados, descritivos e fáceis de reverter
- [ X ] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [ X ] Meu código está seguindo os padrões de acessibilidade

---

## Outras observações

### Executando Testes E2E da nossa app localmente sem interface:

###### Comando para execução no console
```
nx run e2e:e2e
```

![Portal_Ascepa_Cypress_Teste_E2E_Fdl](https://github.com/user-attachments/assets/b1472a48-6b9a-41a9-b0f5-0baec7cde7cf)

![image](https://github.com/user-attachments/assets/a3b4e566-d98d-4eef-bd18-5aff13030e9c)
---

### Executando Testes E2E da nossa app com um browser:

###### Comando para execução no console
```
npx nx e2e e2e --watch
```

![image](https://github.com/FelipeDuarteLuna/painel-administrativo/assets/29357935/511bce50-bc07-4360-8a88-018c8ad07d26)

2024-08-01 14:40 UTC, andrewarosario commented on e2e/src/e2e/Accessing-Portal.cy.ts
> +    cy.wait(3000);
Algum motivo para utilizar esse `wait` nesse ponto?

2024-08-01 14:59 UTC, FelipeDuarteLuna commented on e2e/src/e2e/Accessing-Portal.cy.ts
> +    cy.wait(3000);
Nenhum motivo, só pra da um delay e valorizar o trampo. Assim que acessa o site do Portal-Ascepa. Quer que remova ?

2024-08-01 15:15 UTC, andrewarosario commented on e2e/src/e2e/Accessing-Portal.cy.ts
> +    cy.wait(3000);
Perguntei mais pelo fato de ter uma regra do ESLint pra isso. Mas pensando que depois vamos integrar esses testes na Pipeline, quanto mais rápido melhor =)

2024-08-02 15:31 UTC, FelipeDuarteLuna commented on e2e/src/e2e/Accessing-Portal.cy.ts
> +    cy.wait(3000);
Melhoria implementada com Sucesso. Vlw

2024-08-02 17:02 UTC, andrewarosario requested changes

2024-08-02 17:02 UTC, andrewarosario commented on e2e/src/e2e/Accessing-Portal.cy.ts
> +    cy.wait(3000);
Opa mestre, o código ainda tá ali, acho que faltou dar push na branch 😄

2024-08-05 11:32 UTC, FelipeDuarteLuna commented on e2e/src/e2e/Accessing-Portal.cy.ts
> +    cy.wait(3000);
Mestrão, não sei o que houve. Mas agora está feito a melhoria. Vlw

2024-08-05 12:34 UTC, andrewarosario approved these changes

2024-08-05 17:24 UTC, Werisu approved these changes
LGTM 🙏

2024-08-05 18:58 UTC, merged