feat: add label component
techexpertspro/portal-ascepa pull request #136
Opened 2024-08-03 15:56 UTC by gfrabelo

## Descrição

Cria o componente Label.

![pr-label-ascepa](https://github.com/user-attachments/assets/9fd2bc63-d28b-438b-ace2-8218be6266ec)

---

## Tipo da alteração

feat: Uma nova funcionalidade

---

## Checklist

- [x] Revi meu próprio código antes de enviar para revisão
- [x] Testei minha correção ou recurso extensivamente antes de enviar para revisão
- [x] Formatei meu código usando o guia de estilo de interface (Prettier + ESLint)
- [x] Meu código está bem documentado com apenas informações relevantes
- [x] Minhas alterações não geram novos avisos
- [x] Meus commits são bem organizados, descritivos e fáceis de reverter
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Meu código está seguindo os padrões de acessibilidade

---

## Outras observações

---

2024-08-05 12:37 UTC, andrewarosario approved these changes
LGTM!

2024-08-07 22:28 UTC, FelipeDuarteLuna approved these changes
Code Reviews concluído com Sucesso.

2024-08-09 14:17 UTC, Werisu approved these changes
LGTM! 🚀

2024-08-09 15:03 UTC, charlesribeiro approved these changes

2024-08-12 23:15 UTC, andrewarosario commented
@gfrabelo @MatheusAndradeMelo A PR já tá perfeita 🚀 Só precisa resolver os conflitos 😉

2024-08-22 12:58 UTC, andrewarosario requested changes

2024-08-22 12:58 UTC, andrewarosario commented on src/scss/tokens/colors/_token.scss
> +$color-white: #ffffff;
Neste arquivo já existe essa variável `$color-white`, então ela pode ser removida

2024-09-18 13:10 UTC, andrewarosario approved these changes

2024-09-18 14:07 UTC, merged