feat: create header component
techexpertspro/portal-ascepa pull request #138
Opened 2024-08-05 22:38 UTC by ernaneaugusto

## Descrição
- Criação do componente Header com layouts para Web e Mobile(responsivo)
- Adicionado criado novos mixins para padronizar tamanho de borda
  - `src/scss/tokens/generic/_mixin.scss`
  - `src/scss/tokens/generic/_token.scss`
- Adicionado propriedade `box-sizing: border-box` em `src/styles.scss` a todos os componentes para prevenir problemas de dimensão padrão dos componentes
- Alteração da fonte padrão dos elementos do `body` para uma variável que já possuía o valor

---

## Tipo da alteração
feat: Uma nova funcionalidade

---

## Checklist
- [x] Revi meu próprio código antes de enviar para revisão
- [x] Testei minha correção ou recurso extensivamente antes de enviar para revisão
- [x] Formatei meu código usando o guia de estilo de interface (Prettier + ESLint)
- [x] Meu código está bem documentado com apenas informações relevantes
- [x] Minhas alterações não geram novos avisos
- [x] Meus commits são bem organizados, descritivos e fáceis de reverter
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Meu código está seguindo os padrões de acessibilidade

---

## Outras observações
- Já deixamos o componente Header adicionado em `app.component.html` no local onde imaginamos que ele será colocado
- Os links do Header estão 'mockados'

---

2024-08-06 12:25 UTC, andrewarosario requested changes

2024-08-06 12:25 UTC, andrewarosario commented on modules/layout/src/lib/header/header.component.html
> +      (keydown)="onKeyUpSpace($event)"
Deixando o comportamento padrão do button esse evento de Keydown não é mais necessário 😉

2024-08-06 12:25 UTC, andrewarosario commented on modules/layout/src/lib/header/header.component.scss
> +#header {
É uma boa prática utilizar classes ao invés de Id's para os seletores CSS

2024-08-06 12:25 UTC, andrewarosario commented on modules/layout/src/lib/header/header.component.spec.ts
> +  });
Removendo o método `onKeyUpEnter`, esse teste não será mais necessário

2024-08-09 13:49 UTC, Werisu commented on modules/layout/src/lib/header/header.component.html
> +      (keydown)="onKeyUpSpace($event)"
O comportamento padrão do botão já inclui a possibilidade de ser ativado tanto com um clique quanto com a tecla Enter ou Espaço.

2024-08-09 13:54 UTC, Werisu commented on modules/layout/src/lib/header/header.component.spec.ts
> +  });
Removendo a função onKeyUpSpace

2024-08-12 22:50 UTC, ernaneaugusto commented on modules/layout/src/lib/header/header.component.html
> +      (keydown)="onKeyUpSpace($event)"
Top demais pessoal isso resolveu, removi o método do TS e HTML.

2024-08-12 22:54 UTC, ernaneaugusto commented on modules/layout/src/lib/header/header.component.scss
> +#header {
Nesse caso optei por usar ID porque o #header é único e esse seletor não é usado em mais nenhum lugar. Mesmo assim seria melhor colocar uma classe?

2024-08-12 23:11 UTC, andrewarosario commented on modules/layout/src/lib/header/header.component.scss
> +#header {
Nesse caso então tranquilo, man ;)

2024-08-12 23:11 UTC, andrewarosario approved these changes
LGTM 🚀

2024-08-14 13:49 UTC, arthuralveso approved these changes

2024-08-15 17:34 UTC, merged