Feat/quem somos
techexpertspro/portal-ascepa pull request #146
Opened 2024-08-15 18:58 UTC by lukamoura

## Descrição

- Criação do componente Quem somos
- Utilização do componente Quem somos na home
- Adicionei testes simples referente aos Inputs com as informações

---

## Tipo da alteração

feat: Uma nova funcionalidade
---

## Checklist

- [X] Revi meu próprio código antes de enviar para revisão
- [X ] Testei minha correção ou recurso extensivamente antes de enviar para revisão
- [X ] Formatei meu código usando o guia de estilo de interface (Prettier + ESLint)
- [ X] Meu código está bem documentado com apenas informações relevantes
- [X ] Minhas alterações não geram novos avisos
- [X ] Meus commits são bem organizados, descritivos e fáceis de reverter
- [X ] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [X ] Meu código está seguindo os padrões de acessibilidade

---

## Outras observações

- Adicionei o roteamento da Home para que eu consiga entregar o DOD da task
- Adicionei últimas noticias e header a home para começarmos a ver o portal caminhando

---

2024-08-15 19:44 UTC, charlesribeiro commented on modules/home/src/lib/about-us/about-us.component.ts
> +  styleUrl: './about-us.component.scss',
Não estamos usando, pelo menos por enquanto, esse .scss.
Recomendo remover essa linha caso não haja a intenção de usá-lo.

2024-08-15 19:46 UTC, charlesribeiro commented on modules/home/src/lib/about-us/about-us.component.html
> +    <img [src]="imgSrc" [alt]="alternativeText" class="about-us-img" />
A classe about-us-img não é utilizada nem no .scss, nem nos testes unitários. E mesmo se fosse utilizada nos testes unitários, acho mais recomendado testar o elemento via `img`

2024-08-15 19:51 UTC, lukamoura commented on modules/home/src/lib/about-us/about-us.component.ts
> +  styleUrl: './about-us.component.scss',
estou usando esse scss até que a home tenha um layout inclusivo para os componentes, container

2024-08-15 19:52 UTC, lukamoura commented on modules/home/src/lib/about-us/about-us.component.html
> +    <img [src]="imgSrc" [alt]="alternativeText" class="about-us-img" />
sim, criei e acabei nao utilizando, utilizei o img

2024-08-15 19:55 UTC, charlesribeiro requested changes

2024-08-15 19:55 UTC, charlesribeiro commented on modules/home/src/lib/about-us/about-us.component.ts
> +  styleUrl: './about-us.component.scss',
Recomendo remover até que o styleUrl realmente seja utilizado, creio ser arriscado deixar dead code na esperança de que um dia ele vá ser usado de fato.

2024-08-15 19:56 UTC, lukamoura commented on modules/home/src/lib/about-us/about-us.component.ts
> +  styleUrl: './about-us.component.scss',
não consegui responder embaixo, eu estou usando o styleUrl pelo menos por enqto, qdo eu não usar ai sim eu retiro

2024-08-15 20:19 UTC, andrewarosario commented on modules/home/src/lib/home/home.component.html
> +<lib-header></lib-header>
Para manter o componente Header em todas as páginas (não somente a Home page) seria legal deixar ele no `app.component.html`. O que acha?

2024-08-16 00:08 UTC, lukamoura commented on modules/home/src/lib/home/home.component.html
> +<lib-header></lib-header>
sim, fiquei na duvida

2024-08-16 00:20 UTC, lukamoura commented on modules/home/src/lib/home/home.component.html
> +<lib-header></lib-header>
feito

2024-08-16 01:52 UTC, charlesribeiro requested changes

2024-08-16 14:59 UTC, andrewarosario approved these changes

2024-08-19 18:17 UTC, Werisu approved these changes
LGTM!

2024-08-19 19:52 UTC, charlesribeiro approved these changes

2024-08-19 21:56 UTC, merged