Componente "Filie-se" com suporte para desktop
techexpertspro/portal-ascepa pull request #172
Opened 2024-09-13 19:06 UTC by victoralvesprof

## Descrição

Implementação do componente "Filie-se" à Home do portal.

## Tipo da alteração

feat: Uma nova funcionalidade

## Checklist

- [x] Revi meu próprio código antes de enviar para revisão
- [x] Testei minha correção ou recurso extensivamente antes de enviar para revisão
- [x] Formatei meu código usando o guia de estilo de interface (Prettier + ESLint)
- [x] Meu código está bem documentado com apenas informações relevantes
- [x] Minhas alterações não geram novos avisos
- [x] Meus commits são bem organizados, descritivos e fáceis de reverter
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Meu código está seguindo os padrões de acessibilidade

## Outras observações

O componente "Filie-se" foi implementado apenas para visualização em telas desktop usando Flexbox. A versão para dispositivos móveis ainda não foi desenvolvida e será implementada posteriormente.

2024-09-13 22:10 UTC, charlesribeiro commented
Não vejo muito sentido em parametrizar o componente com @Input neste caso específico, já que o conteúdo é estático e só será modificado em algumas ocasiões (quando o site for refatorado). O uso de @Input se justifica mais quando os dados são dinâmicos ou variáveis com frequência, o que não parece ser o caso aqui. 


[joinUs]="{
    title: 'Filie-se',
    text: aboutUsText,
    imgSrc: imgSrc,
    alternativeText: alternativeText,
    button: 'Saiba mais'
  }"

Algumas razões

**Melhor desempenho:** Se o conteúdo for realmente estático na maior parte do tempo, deixar de usar @Input pode melhorar o desempenho, pois o Angular não precisará verificar mudanças nessas entradas com tanta frequência. Inclusive, podemos usar onPush como estratégia de change detection.

**Manutenção de código:** Como o conteúdo do componente joinUs é basicamente estático (com exceção de poucos elementos como o text e imgSrc), parametrizá-lo pode adicionar complexidade desnecessária ao código. Isso pode fazer com que a manutenção seja mais difícil, especialmente se não houver necessidade real de flexibilizar essas propriedades.

**Separação de responsabilidades:** Ao definir os valores diretamente no componente (em vez de receber via @Input), mantemos a lógica de apresentação separada da lógica de dados. Dessa forma, a renderização fica mais simples e mais fácil de rastrear. Além disso, evita o acoplamento excessivo entre o componente pai (home.component) e os filhos, como o joinUs.


Sugiro que, em vez de usar o @Input para esses elementos, consideremos definir os valores diretamente no template do componente lib-join-us, caso não seja prevista a necessidade de mudar dinamicamente esses dados em várias partes da aplicação. E estes valores podem vir no futuro de uma lib separada e/ou de um service pra tradução.

2024-09-13 22:12 UTC, charlesribeiro requested changes

2024-09-13 22:12 UTC, charlesribeiro commented on modules/home/src/lib/join-us/join-us.component.ts
> +})
Porque este componente não está usando  `changeDetection: ChangeDetectionStrategy.OnPush`? https://medium.com/totvsdevelopers/melhore-a-performance-da-sua-aplica%C3%A7%C3%A3o-com-change-detection-strategy-onpush-4259fc1eb59c

É um excelente candidato, visto que o conteúdo é 100% estático.

2024-09-13 22:12 UTC, charlesribeiro commented on modules/home/src/lib/join-us/join-us.component.html
> +    width="389"
Recomendo extrair este valor para uma variável ou, melhor ainda, mover este valor para um `.scss` (global?)

2024-09-13 22:12 UTC, charlesribeiro commented on modules/home/src/lib/join-us/join-us.component.spec.ts
> +  it('should text h2', () => {
should text?

2024-09-14 01:46 UTC, victoralvesprof commented on modules/home/src/lib/join-us/join-us.component.html
> +    <button style="width: 30%" (click)="learnMore()">
para fins de teste unitarios e de layout esse botao ai. Sei que vai precisar ser refatorado em breve.

2024-09-14 01:48 UTC, victoralvesprof commented on modules/home/src/lib/join-us/join-us.component.ts
> +
criei um arquivo de constants somente para este componente.

2024-09-14 01:48 UTC, victoralvesprof commented on modules/home/src/lib/join-us/join-us.component.ts
> +    console.log('click saiba mais');
so pra teste unitario mesmo.

2024-09-14 01:48 UTC, victoralvesprof commented on modules/home/src/lib/join-us/join-us.component.ts
> +})
adicionado

2024-09-14 01:49 UTC, victoralvesprof commented on modules/home/src/lib/join-us/join-us.component.html
> +    width="389"
magic number criado no arquivo de constants deste component. Temporario até criamos um arquivo a nivel da pasta shared.

2024-09-14 01:57 UTC, victoralvesprof commented on modules/home/src/lib/join-us/join-us.component.spec.ts
> +  it('should text h2', () => {
fixed

2024-09-16 04:56 UTC, charlesribeiro approved these changes

2024-09-16 10:48 UTC, Werisu commented on modules/home/src/lib/join-us/join-us.component.ts
> +    console.log('click saiba mais');
Era bom deixar um comentário no código avisando que é para teste unitário.

2024-09-16 10:56 UTC, Werisu commented on modules/home/src/lib/join-us/join-us.component.ts
> +  imports: [CommonModule, NgOptimizedImage],
Interessante esse NgOptimizedImage, é novidade para mim.

"Diretiva que melhora o desempenho de carregamento de imagens, aplicando as melhores práticas." -angular.dev

2024-09-16 10:57 UTC, Werisu approved these changes
LGTM! 🚀

2024-09-18 21:13 UTC, merged