feat(footer): implement footer component
techexpertspro/portal-ascepa pull request #173
Opened 2024-09-16 18:31 UTC by olirock

## Descrição

Criação do componente Footer com layouts para Web e Mobile(responsivo) de acordo com template definido no figma

Desktop
![Captura de Tela 2024-09-16 às 15 28 43](https://github.com/user-attachments/assets/74c857a8-b414-4753-8bb6-d5328ed04dfe)

Mobile
![Captura de Tela 2024-09-16 às 15 30 34](https://github.com/user-attachments/assets/e971bfac-6aba-4116-9a2a-236313dabe49)

---

## Tipo da alteração

feat: Uma nova funcionalidade

---

## Checklist

- [x] Revi meu próprio código antes de enviar para revisão
- [x] Testei minha correção ou recurso extensivamente antes de enviar para revisão
- [x] Formatei meu código usando o guia de estilo de interface (Prettier + ESLint)
- [x] Meu código está bem documentado com apenas informações relevantes
- [x] Minhas alterações não geram novos avisos
- [x] Meus commits são bem organizados, descritivos e fáceis de reverter
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Meu código está seguindo os padrões de acessibilidade

---

## Outras observações

---

2024-09-23 12:24 UTC, FelipeDuarteLuna requested changes
Boa Tarde Guerreiro, Firme ?

Sua implementação funcionou legal, mas precisa realizar 2 ajustes.
I. Utilizar o Tokens de margens e cor;
II. Ajuste o Media Queries, com px não fica renderizando conforme o tamanho.
![image](https://github.com/user-attachments/assets/705d4dbc-0601-4749-abb4-d9b7414652ea)

2024-09-23 19:32 UTC, Werisu commented on modules/layout/src/lib/footer/footer.component.scss
> +  padding: 20px;
Remover padding:20px

2024-09-23 19:32 UTC, Werisu commented on modules/layout/src/lib/footer/footer.component.html
> +<footer id="footer">
adicionar a class p-20px

2024-09-23 19:34 UTC, Werisu commented on modules/layout/src/lib/footer/footer.component.scss
> +  margin-top: 20px;
Remover margin-top: 20px

2024-09-23 19:42 UTC, Werisu commented on modules/layout/src/lib/footer/footer.component.scss
> +  background-color: #f8f8f8;
Acredito que não exista essa cor no projeto do figma

[projeto figma](https://www.figma.com/design/3qawe9F2BwNxmGG87aWBzn/Portal-Ascepa?node-id=2092-3&node-type=frame&t=OGJs3yGVIhdt8ycb-0)

utilizar o token $color-white

2024-11-25 22:46 UTC, andrewarosario commented
@olirock Pode atuar nos apontamentos?

2024-12-02 22:36 UTC, andrewarosario commented
Adicionado @FelipeDuarteLuna e @Werisu como responsáveis pelo Pull Request

2024-12-19 18:59 UTC, Werisu commented
## Descrição

#### Objetivo
Incorporar melhorias de acessibilidade e informações atualizadas no componente de rodapé, além de tornar a classe `sr-only` reutilizável em todo o projeto.

#### Alterações Realizadas
1. **Arquivo `_global.scss`**:
   - Adicionada a classe `.sr-only` para esconder elementos visualmente enquanto os mantém acessíveis para tecnologias assistivas.

2. **HTML do Rodapé**:
   - Atualizado o endereço com detalhes completos, incluindo bairro, CEP, e cidade/estado.
   - Adicionado link para o site "Tech Experts" com atributos `aria-label`, indicando que o link abre em nova aba.
   - Incorporada a classe `sr-only` para ocultar texto redundante visualmente.

#### Benefícios
- **Acessibilidade**:
  - O uso de `.sr-only` melhora a experiência para usuários de leitores de tela.
  - O atributo `aria-label` no link comunica claramente a funcionalidade de abrir em nova aba.
- **Manutenção**:
  - A inclusão da classe `.sr-only` no escopo global evita duplicação e promove padronização.
- **Atualização Informativa**:
  - O endereço do rodapé agora reflete informações mais precisas e completas.

#### Impacto
- **Acessibilidade**: Melhor suporte para leitores de tela e navegação assistiva.
- **Estilização**: Nenhum impacto significativo no layout visual.
- **SEO**: O link externo adicionado melhora a conectividade do site.

#### Testes Recomendados
1. **Validação de Acessibilidade**:
   - Use Lighthouse para verificar a acessibilidade do rodapé.
   - Teste com leitores de tela como NVDA ou VoiceOver para confirmar a funcionalidade do link e o uso de `aria-label`.
   - Validação de contraste das cores no rodapé.
![image](https://github.com/user-attachments/assets/0a81daec-b05a-46a6-99d2-ecd6a06b0dcf)
   - Testes manuais em leitores de tela (NVDA, VoiceOver) para verificar a navegação.
![image](https://github.com/user-attachments/assets/8d9eec75-95a0-4c92-9535-79809ddbfac2)
   - Verificação de compatibilidade em diferentes navegadores e dispositivos.
2. **Validação de Estilos**:
   - Verifique se a classe `.sr-only` está funcionando corretamente e não afeta o layout visual.
3. **Testes de Navegador**:
   - Teste o comportamento do link em diferentes navegadores e dispositivos, garantindo que abre corretamente em nova aba.

Se houver necessidade de ajustes ou adições, por favor, avise! 😊

2024-12-19 19:28 UTC, Werisu commented
## **Descrição**

#### **Objetivo**
Adicionar testes unitários ao componente de rodapé (`footer.component.spec.ts`) para verificar conformidade com requisitos de acessibilidade e garantir a integridade dos elementos renderizados.

![image](https://github.com/user-attachments/assets/0de5d3dc-bd90-4ea4-9ea1-b76b5ddd462c)

#### **Alterações Realizadas**
1. **Testes de Acessibilidade**:
   - Verificação da presença de atributos ARIA no `<footer>` e no link externo.
   - Validação da aplicação da classe `.sr-only` para elementos acessíveis escondidos.
   - Testes para garantir que o link externo possui atributos de segurança (`target="_blank"`, `rel="noopener noreferrer"`).

2. **Testes Funcionais**:
   - Renderização dinâmica do ano atual no rodapé.
   - Verificação da presença e do conteúdo dos elementos principais (título, endereço, direitos autorais).
   - Validação da ordem correta dos elementos no DOM, garantindo consistência para leitores de tela.

#### **Benefícios**
- **Acessibilidade**: Garante que o rodapé está em conformidade com boas práticas de acessibilidade.
- **Manutenção**: Os testes cobrem elementos essenciais do componente, reduzindo o risco de regressões futuras.
- **Qualidade**: Melhora a confiabilidade do código ao adicionar cobertura de testes para cenários comuns.

#### **Como Testar**
1. Execute os testes unitários:
   ```bash
   npx nx run layout:test
   ```
2. Confirme que todos os testes no arquivo `footer.component.spec.ts` passam com sucesso.
3. Utilize ferramentas como Lighthouse para verificar a acessibilidade do rodapé após as alterações.

#### **Impacto**
- **Testes**: Aumenta a cobertura de testes para o componente de rodapé.
- **Acessibilidade**: Melhora a experiência para usuários de leitores de tela.
- **Conformidade**: Assegura práticas seguras e padrões de acessibilidade em links externos.

LGTM! 😊🚀

2025-01-06 22:46 UTC, FelipeDuarteLuna approved these changes
Code review realizado com Sucesso, OK.

2025-04-02 22:27 UTC, darianeabich approved these changes
Code review realizado com sucesso.

2025-04-02 22:27 UTC, merged