docs: add readme badges
techexpertspro/portal-ascepa pull request #72
Opened 2024-06-19 01:34 UTC by Agemiro

## Descrição

Inclusão de badges do Readme

## Tipo da alteração

docs: add readme badges

## Checklist

- [x] Revi meu próprio código antes de enviar para revisão
- [x] Testei minha correção ou recurso extensivamente antes de enviar para revisão
- [x] Formatei meu código usando o guia de estilo de interface (Prettier + ESLint)
- [x] Meu código está bem documentado com apenas informações relevantes
- [x] Minhas alterações não geram novos avisos
- [x] Meus commits são bem organizados, descritivos e fáceis de reverter
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Meu código está seguindo os padrões de acessibilidade

2024-06-19 12:21 UTC, andrewarosario requested changes

2024-06-19 12:21 UTC, andrewarosario commented on README.md
> +![GitHub Actions Workflow Status](https://img.shields.io/github/actions/workflow/status/techexpertspro/portal-ascepa/ci.yml) ![GitHub last commit](https://img.shields.io/github/last-commit/techexpert
Acho que seria bacana referenciar o workflow `deploy.yml` em vez do `ci.yml`. O Workflow do CI roda o build a toda Pull Request aberta, e nela é mais comum que ele falhe.
Agora o Workflow de deploy vai rodar o build somente quando tiver código que vai subir pra `main`. Nessa etapa sabemos que ele foi revisado e validado. Pode refletir melhor o status atual do nosso build 😉 
```suggestion
![GitHub Actions Workflow Status](https://img.shields.io/github/actions/workflow/status/techexpertspro/portal-ascepa/deploy.yml) ![GitHub last commit](https://img.shields.io/github/last-commit/techexpertspro/portal-ascepa) ![Static Badge](https://img.shields.io/badge/code_style-prettier-ff69b4)
```

2024-06-19 12:41 UTC, andrewarosario approved these changes
Esse README tá ficando bonito demais ❤️

2024-06-20 11:28 UTC, willflame approved these changes

2024-06-20 11:28 UTC, merged