ci: add sonarcloud
techexpertspro/portal-ascepa pull request #75
Opened 2024-06-20 22:50 UTC by FelipeDuarteLuna

feat/ci: Adicionado a execução do SonarCloud no setup da pipeline, para análise do código, scaner e identificar code's smells.

Projeto Mentoria Angular PRO | Tech Experts: https://sonarcloud.io/organizations/techexpertspro/projects

https://sonarcloud.io/project/overview?id=portal-ascepa

![image](https://github.com/techexpertspro/portal-ascepa/assets/29357935/8576d982-c4b8-452d-bf44-a2bbacef9504)

---

## Tipo da alteração

feat/ci: Add SonarCloud a pipeline do GitActions

---

## Checklist

- [ X  ] Revi meu próprio código antes de enviar para revisão
- [ X ] Testei minha correção ou recurso extensivamente antes de enviar para revisão
- [ X ] Formatei meu código usando o guia de estilo de interface (Prettier + ESLint)
- [ X ] Meu código está bem documentado com apenas informações relevantes
- [ X ] Minhas alterações não geram novos avisos
- [ X ] Meus commits são bem organizados, descritivos e fáceis de reverter
- [ X ] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [ X ] Meu código está seguindo os padrões de acessibilidade

---

## Outras observações

Não há

---

2024-06-20 23:36 UTC, FelipeDuarteLuna commented
https://sonarcloud.io/summary/new_code?id=portal-ascepa&pullRequest=75

![image](https://github.com/techexpertspro/portal-ascepa/assets/29357935/becde446-697d-4e0b-aa2c-0b893e9bcd32)

2024-06-20 23:49 UTC, RenanBotelho approved these changes
Code review realizado com sucesso.

2024-06-21 00:28 UTC, andrewarosario requested changes

2024-06-21 00:28 UTC, andrewarosario commented on sonar-project.properties
> +sonar.sources=src/app
Vamos precisar acrescentar também o diretório `modules`. Lá que ficarão os demais módulos do projeto.

2024-06-21 00:43 UTC, andrewarosario requested changes

2024-06-21 00:43 UTC, andrewarosario commented on .github/workflows/sonarcloud-scan.yml
> +
Nesse workflow de análise do Sonar pra branch `main`, precisamos de um step para rodar os testes de toda a app antes de fazer o scan. Acho que seria algo mais ou menos assim:
```
- name: Test code
  run: npx nx run-many -t test --parallel=3 --configuration=ci --code-coverage --coverageReporters=lcov
```

2024-06-21 14:41 UTC, FelipeDuarteLuna commented on sonar-project.properties
> +sonar.sources=src/app
Corrigido. Vlw

2024-06-21 14:43 UTC, FelipeDuarteLuna commented on .github/workflows/sonarcloud-scan.yml
> +
Entendi, ao invés de executar a execução do código somente para os arquivos que estão sendo alterados . é para análisar o projeto inteiro ?

Trocar o comando run: npx nx affected -t test --parallel=3 --configuration=ci --code-coverage --coverageReporters=lcov, pelo run: npx nx run-many -t test --parallel=3 --configuration=ci --code-coverage --coverageReporters=lcov ?

2024-06-21 16:00 UTC, andrewarosario commented on .github/workflows/sonarcloud-scan.yml
> +
Opa mestre, na verdade teremos 2 análises do Sonar durante o fluxo:

A primeira é a análise parcial por Pull Request. O Sonar vai rodar somente nos arquivos afetados. E isso já ta fazendo corretamente pelo arquivo `ci.yml`.

A segunda análise é a análise completa do projeto todo, que é quando a Pull Request é mergeada para a branch `main`. Isso vai ser feito pelo arquivo `sonarcloud-scan.yml` que você criou. Nesse arquivo precisamos colocar esse step de rodar todos os testes.

2024-06-21 16:21 UTC, FelipeDuarteLuna commented on .github/workflows/sonarcloud-scan.yml
> +
Entendi Mestrão... Fo implementado e testado.

2024-06-21 17:00 UTC, andrewarosario approved these changes
LGTM 💯

2024-06-21 19:05 UTC, merged